ring_buffer_test: ring_buffer_test.cpp ring_buffer.template ring_buffer.hpp
	/opt/irods-externals/clang3.8-0/bin/clang++  -o ring_buffer_test ring_buffer_test.cpp -I/opt/irods-externals/boost1.60.0-0/include -stdlib=libc++ -std=c++14 -lrt -pthread -lc++abi -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib

test1: test1.cpp
	/opt/irods-externals/clang3.8-0/bin/clang++ -o test1 -I/opt/irods-externals/boost1.60.0-0/include -stdlib=libc++ -std=c++14 test1.cpp -lrt -pthread -lc++abi -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib

list_objects: list_objects.cpp
	/opt/irods-externals/clang3.8-0/bin/clang++ -o list_objects -I/opt/irods-externals/boost1.60.0-0/include -I/opt/irods-externals/aws-sdk-cpp1.4.89-0/include -stdlib=libc++ -std=c++14 list_objects.cpp -lrt -pthread -lc++abi -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/opt/irods-externals/aws-sdk-cpp1.4.89-0/lib -laws-cpp-sdk-core -laws-cpp-sdk-s3 -Wl,-rpath,/opt/irods-externals/aws-sdk-cpp1.4.89-0/lib

put_object_async: put_object_async.cpp
	/opt/irods-externals/clang3.8-0/bin/clang++ -o put_object_async -I/opt/irods-externals/boost1.60.0-0/include -I/opt/irods-externals/aws-sdk-cpp1.4.89-0/include -stdlib=libc++ -std=c++14 put_object_async.cpp -lrt -pthread -lc++abi -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/opt/irods-externals/aws-sdk-cpp1.4.89-0/lib -laws-cpp-sdk-core -laws-cpp-sdk-s3 -Wl,-rpath,/opt/irods-externals/aws-sdk-cpp1.4.89-0/lib

#multipart_upload_aws: multipart_upload_aws.cpp
#	/opt/irods-externals/clang3.8-0/bin/clang++ -g -o multipart_upload_aws -std=c++11 -I/opt/irods-externals/boost1.60.0-0/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-core/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-s3/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-transfer/include multipart_upload_aws.cpp -lc++abi -lz -lrt -pthread -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-core -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-s3 -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-transfer -L/home/jjames/github/aws-sdk-cpp/bld/.deps/install/lib -laws-checksums -laws-cpp-sdk-core -laws-cpp-sdk-s3 -laws-cpp-sdk-transfer -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-core -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-s3 -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-transfer -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/.deps/install/lib

multipart_upload_aws: multipart_upload_aws.cpp
	g++ -g -o multipart_upload_aws -std=c++11 -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-core/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-s3/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-transfer/include multipart_upload_aws.cpp -lz -lrt -pthread -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-core -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-s3 -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-transfer -L/home/jjames/github/aws-sdk-cpp/bld/.deps/install/lib -laws-checksums -laws-cpp-sdk-core -laws-cpp-sdk-s3 -laws-cpp-sdk-transfer -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-core -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-s3 -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-transfer -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/.deps/install/lib
#	g++ -g -o multipart_upload_aws -std=c++11 -I/opt/irods-externals/boost1.60.0-0/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-core/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-s3/include -I/home/jjames/github/aws-sdk-cpp/aws-cpp-sdk-transfer/include multipart_upload_aws.cpp -lz -lrt -pthread -L/opt/irods-externals/boost1.60.0-0/lib/ -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-core -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-s3 -L/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-transfer -L/home/jjames/github/aws-sdk-cpp/bld/.deps/install/lib -laws-checksums -laws-cpp-sdk-core -laws-cpp-sdk-s3 -laws-cpp-sdk-transfer -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-core -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-s3 -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/aws-cpp-sdk-transfer -Wl,-rpath,/home/jjames/github/aws-sdk-cpp/bld/.deps/install/lib
#
read_bytes: read_bytes.cpp
	/opt/irods-externals/clang3.8-0/bin/clang++ -o read_bytes -I/opt/irods-externals/boost1.60.0-0/include -I/opt/irods-externals/aws-sdk-cpp1.4.89-0/include -stdlib=libc++ -std=c++14 read_bytes.cpp -lrt -pthread -lc++abi -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/opt/irods-externals/aws-sdk-cpp1.4.89-0/lib -laws-cpp-sdk-core -laws-cpp-sdk-s3 -Wl,-rpath,/opt/irods-externals/aws-sdk-cpp1.4.89-0/lib

multipart_upload_libs3: multipart_upload_libs3.cpp circular_buffer.hpp 
	/opt/irods-externals/clang3.8-0/bin/clang++ multipart_upload_libs3.cpp -g -o multipart_upload_libs3 -std=c++14 -I/opt/irods-externals/jansson2.7-0/include -I/opt/irods-externals/boost1.60.0-0/include -I/opt/irods-externals/libs3a30e55e8-0/include -stdlib=libc++ -lboost_system -lcrypto -lz -lrt -ls3 -pthread -lc++abi -L/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/opt/irods-externals/libs3a30e55e8-0/lib -I/usr/include/irods -I/usr/include/libxml2 -Wl,-rpath,/opt/irods-externals/boost1.60.0-0/lib/ -Wl,-rpath,/opt/irods-externals/libs3a30e55e8-1/lib /opt/irods-externals/jansson2.7-0/lib/libjansson.a

test: test.cpp s3_multipart_shared_data.hpp shared_memory_object.hpp
	/opt/irods-externals/clang6.0-0/bin/clang++ test.cpp -g -o test -std=c++17 -I/opt/irods-externals/json3.1.2-0/include -I. -I/opt/irods-externals/jansson2.7-0/include -I/opt/irods-externals/boost1.67.0-0/include -I/opt/irods-externals/libs3a30e55e8-0/include -stdlib=libc++ -lboost_system -lboost_filesystem -lcrypto -lz -lrt -ls3 -pthread -lc++abi -L/opt/irods-externals/boost1.67.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/opt/irods-externals/libs3a30e55e8-0/lib -I/usr/include/irods -I/usr/include/libxml2 -Wl,-rpath,/opt/irods-externals/boost1.67.0-0/lib/ -Wl,-rpath,/opt/irods-externals/libs3a30e55e8-1/lib /opt/irods-externals/jansson2.7-0/lib/libjansson.a -lirods_server -lirods_common 

s3_transport_test: s3_transport_test.cpp s3_transport.hpp circular_buffer.hpp scoped_lock.hpp s3_multipart_shared_data.hpp s3_transport.cpp s3_transport_types.hpp s3_transport_util.hpp s3_transport_callbacks.hpp
	/opt/irods-externals/clang6.0-0/bin/clang++ s3_transport_test.cpp s3_transport.cpp -g -o s3_transport_test -std=c++17 -I/opt/irods-externals/json3.1.2-0/include -I. -I/opt/irods-externals/jansson2.7-0/include -I/opt/irods-externals/boost1.67.0-0/include -I/opt/irods-externals/libs3a30e55e8-0/include -stdlib=libc++ -lboost_system -lboost_filesystem -lcrypto -lz -lrt -ls3 -pthread -lc++abi -L/opt/irods-externals/boost1.67.0-0/lib/ -Wl,-rpath,/opt/irods-externals/clang-runtime3.8-0/lib -L/opt/irods-externals/libs3a30e55e8-0/lib -I/usr/include/irods -I/usr/include/libxml2 -Wl,-rpath,/opt/irods-externals/boost1.67.0-0/lib/ -Wl,-rpath,/opt/irods-externals/libs3a30e55e8-1/lib /opt/irods-externals/jansson2.7-0/lib/libjansson.a -lirods_server -lirods_common 
